### ISSUE TITLE
sanity document validation fails

### ISSUE THREAD

**Issue by dmorda** [cositehq/sanity-plugin-simpler-color-input#6]
Sanity introduced a new feature to their CLI that allows you to [validate documents, schema](https://www.sanity.io/changelog/34ea89ee-82cd-401e-8250-846068d11a2d), etc. However, it seems there may be an issue when trying to use it with this plugin.

```
$ sanity schema validate
⠙ Validating schema…
/Volumes/Development/Websites/studio.domain.com/node_modules/@uiw/react-color/src/index.tsx:1
export * from '@uiw/color-convert';
^^^^^^
SyntaxError: Unexpected token 'export'
    at Object.newLoader [as .tsx] (/Volumes/Development/Websites/studio.domain.com/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.<anonymous> (/Volumes/Development/Websites/studio.domain.com/node_modules/sanity-plugin-simpler-color-input/dist/index.js:13:13)```

I could totally be doing something wrong, but so far I've been unable to figure out how to get around this one.

**Comment by dangreaves** [comment]
The `sanity graphql deploy` command also fails with this same error.

The reason is because this package is importing `@uiw/react-color/src/index`, rather than `@uiw/react-color`. This causes Sanity to try and build from source, but since it's imported from a CJS file, it doesn't understand the ESM.

https://github.com/cositehq/sanity-plugin-simpler-color-input/blob/main/src/ColorInput.tsx#L24

Ideally this package would be importing `@uiw/react-color` which would avoid this problem, but looks like there is an open issue in `@uiw/react-color` end preventing this.

https://github.com/uiwjs/react-color/issues/104

**Comment by tuomasorhanen** [comment]
@dangreaves did you come up with a solution to this issue?
