### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by trangluong96** [cositehq/sanity-plugin-simpler-color-input#9]
I use this plugin for my TypeScript Next.js Sanity project and I'm encountering the following issue. Please help me to address it.

package.json
`"sanity-plugin-simpler-color-input": "^2.2.1"`

Sanity Config File

```
import { visionTool } from "@sanity/vision";
import { defineConfig, Slug } from "sanity";
import { structureTool } from "sanity/structure";

// Go to https://www.sanity.io/docs/api-versioning to learn how API versioning works
import { apiVersion, dataset, projectId } from "./src/sanity/env";
import { schema } from "./src/sanity/schema";
import { media } from "sanity-plugin-media";
import { dashboardTool } from "@sanity/dashboard";
import { netlifyWidget } from "sanity-plugin-dashboard-widget-netlify";
import { simplerColorInput } from "sanity-plugin-simpler-color-input";

export default defineConfig({
  basePath: "/studio",
  projectId,
  dataset,
  // Add and edit the content schema in the './sanity/schema' folder
  schema,
  document: {
    productionUrl: async (prev, context) => {
      // context includes the client and other details
      const { dataset, document } = context;
      let resource = document._type || "";
      let slug = (document?.slug as Slug)?.current;

      const params = new URLSearchParams();

      params.set("preview", "true");
      params.set("dataset", dataset);

      if (resource === "tour") {
        resource = "feature-tours";
      }

      if (resource === "page") {
        slug = document?.slug as string;
      }

      return `${window.location.origin}/api/preview?resource=${resource}&slug=${slug}`;
    },
  },
  plugins: [
    structureTool(),
    // Vision is a tool that lets you query your content with GROQ in the studio
    // https://www.sanity.io/docs/the-vision-plugin
    visionTool({ defaultApiVersion: apiVersion }),
    media(),
    simplerColorInput({
      defaultColorList: [
        { label: "Dark Blue", value: "#00488E" },
        { label: "Light Blue", value: "#48A1D9" },
        { label: "Yellow", value: "#FFE926" },
        { label: "Orange", value: "#FF6A31" },
        { label: "Custom...", value: "custom" },
      ],
    }),
  ],
});
```

schema file

```
import { defineType, defineArrayMember } from "sanity";

/**
 * This is the schema type for block content used in the post document type
 * Importing this type into the studio configuration's `schema` property
 * lets you reuse it in other document types with:
 *  {
 *    name: 'someName',
 *    title: 'Some title',
 *    type: 'blockContent'
 *  }
 */

export default defineType({
  title: "Block Content",
  name: "blockContent",
  type: "array",
  of: [
    defineArrayMember({
      title: "Block",
      type: "block",
      // Styles let you define what blocks can be marked up as. The default
      // set corresponds with HTML tags, but you can set any title or value
      // you want, and decide how you want to deal with it where you want to
      // use your content.
      styles: [{ title: "Normal", value: "normal" }],
      lists: [{ title: "Bullet", value: "bullet" }],
      // Marks let you mark up inline text in the Portable Text Editor
      marks: {
        // Decorators usually describe a single property – e.g. a typographic
        // preference or highlighting
        decorators: [
          { title: "Strong", value: "strong" },
          { title: "Emphasis", value: "em" },
        ],
        // Annotations can be any object structure – e.g. a link or a footnote.
        annotations: [
          {
            title: "URL",
            name: "link",
            type: "object",
            fields: [
              {
                title: "URL",
                name: "href",
                type: "url",
              },
            ],
          },
          {
            type: "textColor",
          },
        ],
      },
    }),
    // You can add additional types here. Note that you can't use
    // primitive types such as 'string' and 'number' in the same array
    // as a block type.
    defineArrayMember({
      type: "image",
      options: { hotspot: true },
      fields: [
        {
          name: "alt",
          type: "string",
          title: "Alternative Text",
        },
      ],
    }),
  ],
});
```

Error

```
ReferenceError: window is not defined
at Object.<anonymous> (/opt/build/repo/node_modules/@uiw/react-color-chrome/cjs/EyeDropper.js:11:73)
at Module._compile (node:internal/modules/cjs/loader:1256:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
at Module.load (node:internal/modules/cjs/loader:1119:32)
at Module._load (node:internal/modules/cjs/loader:960:12)
at Module.require (node:internal/modules/cjs/loader:1143:19)
at mod.require (/opt/build/repo/node_modules/next/dist/server/require-hook.js:65:28)
at require (node:internal/modules/cjs/helpers:119:18)
at Object.<anonymous> (/opt/build/repo/node_modules/@uiw/react-color-chrome/cjs/index.js:22:19)
at Module._compile (node:internal/modules/cjs/loader:1256:14)
> Build error occurred
Error: Failed to collect page data for /studio/[[...index]]
at /opt/build/repo/node_modules/next/dist/build/utils.js:1268:15 {
type: 'Error'
}
```

![Screenshot 2024-05-20 at 02 15 56](https://github.com/cositehq/sanity-plugin-simpler-color-input/assets/107823767/254e3aa9-01ca-437a-ba87-d8041f733889)

**Comment by AlyssaKirstine** [comment]
@trangluong96 Sorry it took me a little bit of time to get to this. This is fixed now in [v2.2.2](https://github.com/cositehq/sanity-plugin-simpler-color-input/releases/tag/v2.2.2)!
